minimum_pre_commit_version: "3.6.0"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key

- repo: https://github.com/bwhmather/ssort
  rev: 0.15.0
  hooks:
  - id: ssort

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.12.12
  hooks:
    - id: ruff-format
      language_version: python3.12
      types_or: [ python, pyi ]
    - id: ruff-check
      args: [--fix, --exit-non-zero-on-fix]
      types_or: [ python, pyi ]
      language_version: python3.12

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (imports)
      args: ["--profile=black"]
      types_or: [ python, pyi ]
      language_version: python3.12

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.28.0
  hooks:
    - id: gitleaks

- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.4  # Replace with latest tag
  hooks:
    - id: commitizen
    - id: commitizen-branch
      stages: [pre-push]

- repo: https://github.com/facebook/pyrefly-pre-commit
  rev: 0.0.1
  hooks:
    - id: pyrefly-typecheck-system
      name: Pyrefly (type checking)
      pass_filenames: true # Recomended to do full repo checks. However, you can change this to `true` to only check changed files
